// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4kChGEs_mEth6eiZvpowZ73pmWha4_sA',
    appId: '1:69072610754:web:2a7581ba0e7ca52f0ba25b',
    messagingSenderId: '69072610754',
    projectId: 'sarround-a877b',
    authDomain: 'sarround-a877b.firebaseapp.com',
    storageBucket: 'sarround-a877b.appspot.com',
    measurementId: 'G-6D6M3JZ9ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZmMo0-37Qm0MUVgIWB9UlCJVWAQwrUh0',
    appId: '1:69072610754:android:40d39d42292939b90ba25b',
    messagingSenderId: '69072610754',
    projectId: 'sarround-a877b',
    storageBucket: 'sarround-a877b.appspot.com',
    androidClientId: 'com.example.musicproject'
    
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcjxzRP7pSaoxoUCGmfSlO5EChLAou6Z4',
    appId: '1:69072610754:ios:112dbb4296958dca0ba25b',
    messagingSenderId: '69072610754',
    projectId: 'sarround-a877b',
    storageBucket: 'sarround-a877b.appspot.com',
    iosBundleId: 'com.example.musicproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcjxzRP7pSaoxoUCGmfSlO5EChLAou6Z4',
    appId: '1:69072610754:ios:112dbb4296958dca0ba25b',
    messagingSenderId: '69072610754',
    projectId: 'sarround-a877b',
    storageBucket: 'sarround-a877b.appspot.com',
    iosBundleId: 'com.example.musicproject',
  );
}
